# Generated by Django 2.2.13 on 2020-10-19 08:40

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backManage', '0005_auto_20201019_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='paper_commit',
            field=models.FileField(null=True, upload_to='commit', validators=[django.core.validators.FileExtensionValidator(['pdf'], message='承诺书必须为pdf格式')], verbose_name='承诺书pdf版'),
        ),
        migrations.AddField(
            model_name='work',
            name='paper_game_data',
            field=models.FileField(null=True, upload_to='game_data', validators=[django.core.validators.FileExtensionValidator(['zip'], message='原始数据必须为zip格式')], verbose_name='原始数据zip版'),
        ),
        migrations.AddField(
            model_name='work',
            name='paper_sign_up',
            field=models.FileField(null=True, upload_to='sign_up', validators=[django.core.validators.FileExtensionValidator(['doc', 'docx'], message='报名表必须为doc/docx格式')], verbose_name='报名表word版'),
        ),
        migrations.AlterField(
            model_name='college',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 19, 8, 40, 18, 472502, tzinfo=utc), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 19, 8, 40, 18, 474650, tzinfo=utc), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='judge',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 19, 8, 40, 18, 481161, tzinfo=utc), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='member',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 19, 8, 40, 18, 475735, tzinfo=utc), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='team',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 19, 8, 40, 18, 477382, tzinfo=utc), verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='work',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 19, 8, 40, 18, 479530, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='work',
            name='paper_cc',
            field=models.FileField(null=True, upload_to='cc', validators=[django.core.validators.FileExtensionValidator(['pdf'], message='查重报告必须为pdf格式')], verbose_name='查重报告pdf版'),
        ),
    ]
